### ISSUE TITLE
Codi javascript incrustat en index.html. Es pot implementar amb Alpinejs.

### ISSUE THREAD

**Issue by danieljesusgarcia** [2DAM-202324-PROJECTE/ProjecteTeamFlick#42]
Proveu d'eliminar aquest codi dins d'index.html. És una funcionalitat que es pot implementar amb Alpine fent servir @click, x-data, x-show de manera similar a com funciona el menú per a mòbil.
                <script>
                    let currentOpenContentId = null;

                    function toggleContent(elementId) {
                        const content = document.getElementById(elementId);

                        if (currentOpenContentId && currentOpenContentId !== elementId) {
                            const currentOpenContent = document.getElementById(currentOpenContentId);
                            currentOpenContent.classList.add('hidden');
                        }

                        content.classList.toggle('hidden');
                        currentOpenContentId = content.classList.contains('hidden') ? null : elementId;
                    }
                </script>

**Comment by danieljesusgarcia** [comment]
Mateix problema per toggleFAQ. Es pot implementar fàcilment amb alpine i eliminar el codi següent:

        
        <script>
            function toggleFAQ(faqId) {
                var element = document.getElementById(faqId);
                element.classList.toggle("hidden");
            }
        </script>

**Comment by SergioBertomeu** [comment]
ok vaig a probar-ho
